[project]
name = 'PIB'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.PIB]
path = 'contracts/PIB.clar'
clarity_version = 3
epoch = 3.1

[contracts.PIB-Marketplace]
path = 'contracts/PIB-Marketplace.clar'
clarity_version = 3
epoch = 3.1

[contracts.PIB-Insurance]
path = 'contracts/PIB-Insurance.clar'
clarity_version = 3
epoch = 3.1

[contracts.PIB-Analytics]
path = 'contracts/PIB-Analytics.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
